<?php
/**
 * ExportDatasetApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * opendatasoft
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ExportDatasetApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ExportDatasetApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for exportRecordsCSV
     *
     * .
     *
     */
    public function testExportRecordsCSV()
    {
    }

    /**
     * Test case for exportRecordsGEOJSON
     *
     * .
     *
     */
    public function testExportRecordsGEOJSON()
    {
    }

    /**
     * Test case for exportRecordsICAL
     *
     * .
     *
     */
    public function testExportRecordsICAL()
    {
    }

    /**
     * Test case for exportRecordsJSON
     *
     * .
     *
     */
    public function testExportRecordsJSON()
    {
    }

    /**
     * Test case for exportRecordsOV2
     *
     * .
     *
     */
    public function testExportRecordsOV2()
    {
    }

    /**
     * Test case for exportRecordsSHP
     *
     * .
     *
     */
    public function testExportRecordsSHP()
    {
    }

    /**
     * Test case for exportRecordsXLS
     *
     * .
     *
     */
    public function testExportRecordsXLS()
    {
    }
}
