<?php
/**
 * ExportCatalogApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * opendatasoft
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ExportCatalogApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ExportCatalogApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for exportDatasetsCSV
     *
     * .
     *
     */
    public function testExportDatasetsCSV()
    {
    }

    /**
     * Test case for exportDatasetsJson
     *
     * .
     *
     */
    public function testExportDatasetsJson()
    {
    }

    /**
     * Test case for exportDatasetsRDF
     *
     * .
     *
     */
    public function testExportDatasetsRDF()
    {
    }

    /**
     * Test case for exportDatasetsRSS
     *
     * .
     *
     */
    public function testExportDatasetsRSS()
    {
    }

    /**
     * Test case for exportDatasetsTTL
     *
     * .
     *
     */
    public function testExportDatasetsTTL()
    {
    }

    /**
     * Test case for exportDatasetsXLS
     *
     * .
     *
     */
    public function testExportDatasetsXLS()
    {
    }
}
