<?php
/**
 * OdsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * opendatasoft
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * OdsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OdsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for aggregateDatasets
     *
     * .
     *
     */
    public function testAggregateDatasets()
    {
    }

    /**
     * Test case for aggregateRecords
     *
     * .
     *
     */
    public function testAggregateRecords()
    {
    }

    /**
     * Test case for downloadDatasetAttachement
     *
     * .
     *
     */
    public function testDownloadDatasetAttachement()
    {
    }

    /**
     * Test case for downloadDatasetSnapshot
     *
     * .
     *
     */
    public function testDownloadDatasetSnapshot()
    {
    }

    /**
     * Test case for exportDatasetsCSV
     *
     * .
     *
     */
    public function testExportDatasetsCSV()
    {
    }

    /**
     * Test case for exportDatasetsJson
     *
     * .
     *
     */
    public function testExportDatasetsJson()
    {
    }

    /**
     * Test case for exportDatasetsRDF
     *
     * .
     *
     */
    public function testExportDatasetsRDF()
    {
    }

    /**
     * Test case for exportDatasetsRSS
     *
     * .
     *
     */
    public function testExportDatasetsRSS()
    {
    }

    /**
     * Test case for exportDatasetsTTL
     *
     * .
     *
     */
    public function testExportDatasetsTTL()
    {
    }

    /**
     * Test case for exportDatasetsXLS
     *
     * .
     *
     */
    public function testExportDatasetsXLS()
    {
    }

    /**
     * Test case for exportRecordsCSV
     *
     * .
     *
     */
    public function testExportRecordsCSV()
    {
    }

    /**
     * Test case for exportRecordsGEOJSON
     *
     * .
     *
     */
    public function testExportRecordsGEOJSON()
    {
    }

    /**
     * Test case for exportRecordsICAL
     *
     * .
     *
     */
    public function testExportRecordsICAL()
    {
    }

    /**
     * Test case for exportRecordsJSON
     *
     * .
     *
     */
    public function testExportRecordsJSON()
    {
    }

    /**
     * Test case for exportRecordsOV2
     *
     * .
     *
     */
    public function testExportRecordsOV2()
    {
    }

    /**
     * Test case for exportRecordsSHP
     *
     * .
     *
     */
    public function testExportRecordsSHP()
    {
    }

    /**
     * Test case for exportRecordsXLS
     *
     * .
     *
     */
    public function testExportRecordsXLS()
    {
    }

    /**
     * Test case for getDataset
     *
     * .
     *
     */
    public function testGetDataset()
    {
    }

    /**
     * Test case for getDatasetAttachements
     *
     * .
     *
     */
    public function testGetDatasetAttachements()
    {
    }

    /**
     * Test case for getDatasetFile
     *
     * .
     *
     */
    public function testGetDatasetFile()
    {
    }

    /**
     * Test case for getDatasetReuse
     *
     * .
     *
     */
    public function testGetDatasetReuse()
    {
    }

    /**
     * Test case for getDatasetReuses
     *
     * .
     *
     */
    public function testGetDatasetReuses()
    {
    }

    /**
     * Test case for getDatasetSnapshots
     *
     * .
     *
     */
    public function testGetDatasetSnapshots()
    {
    }

    /**
     * Test case for getDatasets
     *
     * .
     *
     */
    public function testGetDatasets()
    {
    }

    /**
     * Test case for getDatasetsFacets
     *
     * .
     *
     */
    public function testGetDatasetsFacets()
    {
    }

    /**
     * Test case for getMetadataTemplate
     *
     * .
     *
     */
    public function testGetMetadataTemplate()
    {
    }

    /**
     * Test case for getMetadataTemplatesType
     *
     * .
     *
     */
    public function testGetMetadataTemplatesType()
    {
    }

    /**
     * Test case for getMetadataTemplatesTypes
     *
     * .
     *
     */
    public function testGetMetadataTemplatesTypes()
    {
    }

    /**
     * Test case for getPage
     *
     * .
     *
     */
    public function testGetPage()
    {
    }

    /**
     * Test case for getPages
     *
     * .
     *
     */
    public function testGetPages()
    {
    }

    /**
     * Test case for getRecord
     *
     * .
     *
     */
    public function testGetRecord()
    {
    }

    /**
     * Test case for getRecords
     *
     * .
     *
     */
    public function testGetRecords()
    {
    }

    /**
     * Test case for getRecordsFacets
     *
     * .
     *
     */
    public function testGetRecordsFacets()
    {
    }

    /**
     * Test case for getRoot
     *
     * .
     *
     */
    public function testGetRoot()
    {
    }

    /**
     * Test case for getSource
     *
     * .
     *
     */
    public function testGetSource()
    {
    }

    /**
     * Test case for sendDatasetFeedback
     *
     * .
     *
     */
    public function testSendDatasetFeedback()
    {
    }
}
